version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: twitter_user
      POSTGRES_PASSWORD: twitter_password
      POSTGRES_DB: twitter_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U twitter_user -d twitter_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://twitter_user:twitter_password@db:5432/twitter_db
      - SECRET_KEY=production-secret-key-change-me
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
